[project]
name = "sigej"
version = "1.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg[binary,pool]>=3.2.13",
    "python-dotenv>=1.2.1",
    "flask>=3.0.3",
]

[dependency-groups]
scripts = [
    "faker>=38.2.0",
]
